package authorization;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class PathConstants {

    public static final List<String> EMPLOYEE_RESTRICT_PATH_LIST;
    public static final List<String> MANAGER_RESTRICT_PATH_LIST;
    public static final List<String> HR_RESTRICT_PATH_LIST;

    static {
        ArrayList<String> employeeRestrictPaths = new ArrayList<>();
        employeeRestrictPaths.add("/DownloadWorksheet.jsp");
        employeeRestrictPaths.add("/ImportEmployees.jsp");
        employeeRestrictPaths.add("/InsertEmployee.jsp");
        employeeRestrictPaths.add("/ManageNews.jsp");
        employeeRestrictPaths.add("/NavigateRequestForHR.jsp");
        employeeRestrictPaths.add("/NavigateRequestForManager.jsp");
        employeeRestrictPaths.add("/OvertimeScheduleWork.jsp");
        employeeRestrictPaths.add("/ScheduleLeave.jsp");
        employeeRestrictPaths.add("/ScheduleWork.jsp");
        employeeRestrictPaths.add("/ScheduleWorkCalendar.jsp");
        employeeRestrictPaths.add("/ScheduleWorkConflicts.jsp");
        employeeRestrictPaths.add("/ScheduleWorkEmployees.jsp");
        employeeRestrictPaths.add("/ScheduledEmployees.jsp");
        employeeRestrictPaths.add("/ScheduledEmployeeList.jsp");
        employeeRestrictPaths.add("/ShiftManagement.jsp");
        employeeRestrictPaths.add("/UpdateEmployeeByHR.jsp");
        employeeRestrictPaths.add("/UpdateNews.jsp");
        employeeRestrictPaths.add("/ViewAllEmployee.jsp");
        employeeRestrictPaths.add("/ViewDepartment.jsp");
        employeeRestrictPaths.add("/ViewEmployeeWorkSchedule.jsp");
        employeeRestrictPaths.add("/ViewLeaveRequestForHR.jsp");
        employeeRestrictPaths.add("/ViewLeaveRequestForManager.jsp");
        employeeRestrictPaths.add("/ViewOtherRequestListHR.jsp");
        employeeRestrictPaths.add("/ViewOverTimeRequestForHR.jsp");
        employeeRestrictPaths.add("/ViewOverTimeRequestForManager.jsp");
        employeeRestrictPaths.add("/ViewOvertimeByDay.jsp");
        employeeRestrictPaths.add("/viewEmployeesByManager.jsp");
        employeeRestrictPaths.add("/DepartmentServlet");
        employeeRestrictPaths.add("/UpdateDepartmentManagerServlet");
        employeeRestrictPaths.add("/DeleteTempEmployeesServlet");
        employeeRestrictPaths.add("/GetAllEmployeeByHRServlet");
        employeeRestrictPaths.add("/GetEmployeeInfoByHRServlet");
        employeeRestrictPaths.add("/HandleTempEmployeeAJAX");
        employeeRestrictPaths.add("/InsertEmployeeServlet");
        employeeRestrictPaths.add("/InsertImportedEmployeesServlet");
        employeeRestrictPaths.add("/ReadEmployeeFromFileServlet");
        employeeRestrictPaths.add("/searchEmployeeByAjax");
        employeeRestrictPaths.add("/SendEmployeeFormattedFileServlet");
        employeeRestrictPaths.add("/UpdateEmployeeByHRServlet");
        employeeRestrictPaths.add("/UpdateTempEmployeeServlet");
        employeeRestrictPaths.add("/ViewAllEmployeeAjax");
        employeeRestrictPaths.add("/AcceptLeaveRequestServlet");
        employeeRestrictPaths.add("/DenyLeaveRequestServlet");
        employeeRestrictPaths.add("/deletenews");
        employeeRestrictPaths.add("/FilteringByHR");
        employeeRestrictPaths.add("/GetAllNewsByHR");
        employeeRestrictPaths.add("/getdetailnew");
        employeeRestrictPaths.add("/GetInfoNews");
        employeeRestrictPaths.add("/insertNews");
        employeeRestrictPaths.add("/SearchNewsByHR");
        employeeRestrictPaths.add("/updatenews");
        employeeRestrictPaths.add("/addEmployeeOvertime");
        employeeRestrictPaths.add("/addListEmloyeeOvertime");
        employeeRestrictPaths.add("/listAddEmployeeAjax");
        employeeRestrictPaths.add("/listEmployeeOvertimeAjax");
        employeeRestrictPaths.add("/AcceptOTRequestServlet");
        employeeRestrictPaths.add("/DenyOTRequestServlet");
        employeeRestrictPaths.add("/ViewOtherRequestListHR");
        employeeRestrictPaths.add("/DeleteTimesheetForEmployees");
        employeeRestrictPaths.add("/GetConflicts");
        employeeRestrictPaths.add("/GetUnscheduleEmployees");
        employeeRestrictPaths.add("/DeleteShift");
        employeeRestrictPaths.add("/InsertShift");
        employeeRestrictPaths.add("/UpdateShift");
        employeeRestrictPaths.add("/ExportExcelFileServlet");
        employeeRestrictPaths.add("/DownloadWorkSheet");

        ArrayList<String> managerRestrictPaths = new ArrayList<>();
        managerRestrictPaths.add("/DownloadWorksheet.jsp");
        managerRestrictPaths.add("/ImportEmployees.jsp");
        managerRestrictPaths.add("/InsertEmployee.jsp");
        managerRestrictPaths.add("/ManageNews.jsp");
        managerRestrictPaths.add("/NavigateRequestForHR.jsp");
        managerRestrictPaths.add("/OvertimeScheduleWork.jsp");
        managerRestrictPaths.add("/ScheduleLeave.jsp");
        managerRestrictPaths.add("/ScheduleWork.jsp");
        managerRestrictPaths.add("/ScheduleWorkCalendar.jsp");
        managerRestrictPaths.add("/ScheduleWorkConflicts.jsp");
        managerRestrictPaths.add("/ScheduleWorkEmployees.jsp");
        managerRestrictPaths.add("/ScheduledEmployees.jsp");
        managerRestrictPaths.add("/ScheduledEmployeeList.jsp");
        managerRestrictPaths.add("/ShiftManagement.jsp");
        managerRestrictPaths.add("/UpdateEmployeeByHR.jsp");
        managerRestrictPaths.add("/UpdateNews.jsp");
        managerRestrictPaths.add("/ViewAllEmployee.jsp");
        managerRestrictPaths.add("/ViewDepartment.jsp");
        managerRestrictPaths.add("/ViewEmployeeWorkSchedule.jsp");
        managerRestrictPaths.add("/ViewLeaveRequestForHR.jsp");
        managerRestrictPaths.add("/ViewOtherRequestListHR.jsp");
        managerRestrictPaths.add("/ViewOverTimeRequestForHR.jsp");
        managerRestrictPaths.add("/ViewOvertimeByDay.jsp");
        managerRestrictPaths.add("/DepartmentServlet");
        managerRestrictPaths.add("/UpdateDepartmentManagerServlet");
        managerRestrictPaths.add("/DeleteTempEmployeesServlet");
        managerRestrictPaths.add("/GetAllEmployeeByHRServlet");
        managerRestrictPaths.add("/GetEmployeeInfoByHRServlet");
        managerRestrictPaths.add("/HandleTempEmployeeAJAX");
        managerRestrictPaths.add("/InsertEmployeeServlet");
        managerRestrictPaths.add("/InsertImportedEmployeesServlet");
        managerRestrictPaths.add("/ReadEmployeeFromFileServlet");
//        managerRestrictPaths.add("searchEmployeeByAjax");
        managerRestrictPaths.add("/SendEmployeeFormattedFileServlet");
        managerRestrictPaths.add("/UpdateEmployeeByHRServlet");
        managerRestrictPaths.add("/UpdateTempEmployeeServlet");
        managerRestrictPaths.add("/ViewAllEmployeeAjax");
        managerRestrictPaths.add("/deletenews");
        managerRestrictPaths.add("/FilteringByHR");
        managerRestrictPaths.add("/GetAllNewsByHR");
        managerRestrictPaths.add("/getdetailnew");
        managerRestrictPaths.add("/GetInfoNews");
        managerRestrictPaths.add("/insertNews");
        managerRestrictPaths.add("/SearchNewsByHR");
        managerRestrictPaths.add("/updatenews");
        managerRestrictPaths.add("/addEmployeeOvertime");
        managerRestrictPaths.add("/addListEmloyeeOvertime");
        managerRestrictPaths.add("/listAddEmployeeAjax");
        managerRestrictPaths.add("/listEmployeeOvertimeAjax");
//        managerRestrictPaths.add("/AcceptOTRequestServlet");
//        managerRestrictPaths.add("/DenyOTRequestServlet");
        managerRestrictPaths.add("/ViewOtherRequestListHR");
        managerRestrictPaths.add("/DeleteTimesheetForEmployees");
        managerRestrictPaths.add("/GetConflicts");
        managerRestrictPaths.add("/GetUnscheduleEmployees");
        managerRestrictPaths.add("/DeleteShift");
        managerRestrictPaths.add("/InsertShift");
        managerRestrictPaths.add("/UpdateShift");
        managerRestrictPaths.add("/ExportExcelFileServlet");
        managerRestrictPaths.add("/DownloadWorkSheet");
        
        ArrayList<String> hrRestrictPaths = new ArrayList<>();
        hrRestrictPaths.add("/ViewLeaveRequestForManager.jsp");
        hrRestrictPaths.add("/NavigateRequestForManager.jsp");
        hrRestrictPaths.add("/ViewOverTimeRequestForManager.jsp");

        MANAGER_RESTRICT_PATH_LIST = Collections.unmodifiableList(managerRestrictPaths);
        EMPLOYEE_RESTRICT_PATH_LIST = Collections.unmodifiableList(employeeRestrictPaths);
        HR_RESTRICT_PATH_LIST = Collections.unmodifiableList(hrRestrictPaths);
    }

}
